export enum UserTypeEnum {
  USER = 'USER',
  USER_CLIENT = 'USER_CLIENT',
  USER_CUSTOMER = 'USER_CUSTOMER',
  USER_REPRESENTATIVE = 'USER_REPRESENTATIVE',
  EMPLOYEE = 'EMPLOYEE',
  ADMIN = 'ADMIN',
}
