export enum InvoiceStatusesEnum {
  CREADA = 'CREADA',
  ENVIADA = 'ENVIADA',
  RECIBIDA = 'RECIBIDA',
  VERIFICACION = 'VERIFICACION',
  APROBADA = 'APROBADA',
  PENDIENTE = 'PENDIENTE',
  CANCELADA = 'CANCELADA',
  ABONADA = 'ABONADA',
  ARCHIVADA = 'ARCHIVADA',
}
